# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier "tw.zestlifia.fastlane.zestFastlane"
username "wonderfuljack123@gmail.com"