# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # increment_build_number
    match(type: "appstore") # more information: https://codesigning.guide -> llow you to sign your application using your distribution provisioning profile and distribution certificate
    gym(scheme: "zestFastlane") # Build your app - more options available
    pilot
    # pilot(
    #   skip_waiting_for_build_processing: true
    # )
    # clean_build_artifacts
    # commit_version_bump(
    #   message: "Fastlane iOS: Released new build #{lane_context[SharedValues::BUILD_NUMBER]} to Apple TestFlight [ci skip]",
    #   xcodeproj: "./UdemyFastlane.xcodeproj",
    #   force: true
    # )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "zestFastlane.xcodeproj")
    build_app(scheme: "zestFastlane")
    upload_to_app_store
  end

end
